apply plugin: 'elasticsearch.internal-testclusters'
//apply plugin: 'elasticsearch.test-with-dependencies'
apply plugin: 'elasticsearch.internal-es-plugin'

import org.elasticsearch.gradle.internal.info.BuildParams

//apply plugin: 'elasticsearch.internal-yaml-rest-test'
//apply plugin: 'elasticsearch.yaml-rest-compat-test'
apply plugin: 'elasticsearch.internal-es-plugin'
apply plugin: 'elasticsearch.internal-java-rest-test'

esplugin {
  name 'x-pack-autoscaling-qa'
  description 'Plugin for performing QA of autoscaling'
  classname 'org.elasticsearch.xpack.autoscaling.qa.AutoscalingQA'
  extendedPlugins = ['x-pack-autoscaling']
  licenseFile rootProject.file('licenses/SSPL-1.0+ELASTIC-LICENSE-2.0.txt')
  noticeFile rootProject.file('NOTICE.txt')
}

tasks.named("test").configure { enabled = false }

dependencies {

  api project(path: xpackModule('autoscaling'))
  compileOnly project(path: xpackModule('core'))
  testImplementation(testArtifact(project(xpackModule('core'))))
  testImplementation project(path: xpackModule('data-streams'))
  testImplementation project(path: xpackModule('searchable-snapshots'))
  testImplementation project(path: xpackModule('ilm'))

  testImplementation "com.fasterxml.jackson.core:jackson-databind:2.10.4"
  testImplementation project(':modules:transport-netty4') // for http
  testImplementation project(':plugins:transport-nio') // for http
}

//dependencies {
//  yamlRestTestImplementation(testArtifact(project(xpackModule('core'))))
//}
//
//restResources {
//  restApi {
//    include '_common', 'autoscaling'
//  }
//}

testClusters.configureEach {
  testDistribution = 'DEFAULT'
  setting 'xpack.security.enabled', 'true'
  setting 'xpack.license.self_generated.type', 'trial'
  extraConfigFile 'roles.yml', file('autoscaling-roles.yml')
  user username: 'autoscaling-admin', password: 'autoscaling-admin-password', role: 'superuser'
  user username: 'autoscaling-user', password: 'autoscaling-user-password', role: 'autoscaling'
}
